development:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  database: wenti_db
  pool: 5
  username: root
  password: SERVER_PASSWORD
  host: SERVER_IP

production:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  database: wenti_db
  pool: 5
  username: root
  password: SERVER_PASSWORD
  host: SERVER_IP
#rake db:schema:dump
